
<script setup>
// Require authentication and setup
definePageMeta({
  middleware: ['setup', 'auth']
})

// Import components
import JustifiedGallery from '~/components/JustifiedGallery.vue'

// Using custom photo grid layout (Justified Gallery style)

const api = useApi()
const authStore = useAuthStore()
const { $events } = useNuxtApp()

// Fetch real assets from API with pagination
const assets = ref([])
const pending = ref(true)
const loadingMore = ref(false)
const error = ref(null)
const hasNextPage = ref(true)
const nextCursor = ref(null)
const totalCount = ref(0)
const showAssetDialog = ref(false)
const selectedAsset = ref(null)
const sidebarCollapsed = ref(true)
const selectedYear = ref(null)

// JustifiedGallery component handles the layout algorithm

// Fetch initial assets
const fetchAssets = async (reset = true) => {
  try {
    if (reset) {
      pending.value = true
      assets.value = []
      nextCursor.value = null
      hasNextPage.value = true
    } else {
      loadingMore.value = true
    }
    error.value = null
    
    console.log('Fetching assets...', reset ? '(initial)' : '(load more)')
    
    const params = { limit: 50 } // Smaller page size for better performance
    if (nextCursor.value && !reset) {
      // Extract the cursor value from the URL if it's a full URL
      let cursorValue = nextCursor.value
      if (cursorValue.includes('cursor=')) {
        const url = new URL(cursorValue)
        cursorValue = url.searchParams.get('cursor') || cursorValue
      }
      params.cursor = cursorValue
      console.log('Using cursor for pagination:', nextCursor.value)
      console.log('Extracted cursor value:', cursorValue)
    }
    
    const response = await api.assets.list(params)
    console.log('API response:', response)
    console.log('API response data:', response.data)
    console.log('Pagination info:', {
      count: response.data?.count,
      next: response.data?.next,
      previous: response.data?.previous,
      resultsLength: response.data?.results?.length
    })
    
    if (response.success) {
      // The response from DRF with pagination will have a 'results' array
      const assetsList = response.data?.results || response.data || []
      
      if (Array.isArray(assetsList)) {
        console.log('Found assets array with length:', assetsList.length)
        const mappedAssets = assetsList.map(asset => ({
          ...asset,
          // Use the thumbnail and original URLs from the API
          // These are now properly generated by the backend serializer
          faces: asset.faces || []
        }))
        
        if (reset) {
          assets.value = mappedAssets
        } else {
          assets.value = [...assets.value, ...mappedAssets]
        }
        
        console.log('Updated assets array length:', assets.value.length)
        
        // Update pagination state
        hasNextPage.value = !!response.data?.next
        nextCursor.value = response.data?.next || null
        
        console.log('Pagination state:', {
          hasNextPage: hasNextPage.value,
          nextCursor: nextCursor.value,
          totalCount: response.data?.count
        })
        
        // Update total count (only on first load)
        if (reset && response.data?.count !== undefined) {
          totalCount.value = response.data.count
        }
        
        // Debug: Check thumbnail URLs
        if (assets.value.length > 0) {
          console.log('First asset thumbnail_url:', assets.value[0].thumbnail_url)
          console.log('First asset original_url:', assets.value[0].original_url)
          console.log('First asset storage_url:', assets.value[0].storage_url)
        }
      } else {
        console.log('No assets in response or invalid format')
        if (reset) {
          assets.value = []
        }
      }
    } else {
      console.error('API error:', response.error)
      const errorMessage = response.error || 'Failed to fetch assets'
      
      // Handle cursor pagination errors specifically
      if (errorMessage.includes('Invalid cursor') || errorMessage.includes('cursor')) {
        console.log('Cursor pagination error, resetting pagination state')
        // Reset pagination state and try again without cursor
        nextCursor.value = null
        hasNextPage.value = false
        if (!reset) {
          // If this was a "load more" request, just stop trying to load more
          console.log('Stopping pagination due to cursor error')
          return
        }
      }
      
      error.value = new Error(errorMessage)
      if (reset) {
        assets.value = []
      }
    }
  } catch (err) {
    console.error('Error fetching assets:', err)
    error.value = err
    if (reset) {
      assets.value = []
    }
  } finally {
    pending.value = false
    loadingMore.value = false
  }
}

// Load more assets (manual button click)
const loadMoreAssets = async () => {
  if (loadingMore.value || !hasNextPage.value) {
    return
  }
  
  try {
    await fetchAssets(false)
    // Let the masonry handle the layout naturally with overflow-anchor disabled
  } catch (err) {
    console.error('Failed to load more assets:', err)
    // Don't set error state for pagination failures, just log them
    // The user can still see the existing content
  }
}

// Force load more assets (debug function)
const forceLoadMore = async () => {
  console.log('Force loading more assets...')
  console.log('Current state:', {
    hasNextPage: hasNextPage.value,
    nextCursor: nextCursor.value,
    assetsLength: assets.value.length,
    totalCount: totalCount.value
  })
  
  // Reset pagination state and try again
  hasNextPage.value = true
  nextCursor.value = null
  
  try {
    await fetchAssets(false)
  } catch (err) {
    console.error('Force load failed:', err)
  }
}

// Test loading all assets without pagination (debug function)
const testLoadAll = async () => {
  console.log('Testing load all assets...')
  try {
    const response = await api.assets.list({ limit: 1000 }) // Try to get all at once
    console.log('Load all response:', response)
    if (response.success) {
      const assetsList = response.data?.results || response.data || []
      console.log('Total assets from API:', assetsList.length)
      console.log('API count field:', response.data?.count)
    }
  } catch (err) {
    console.error('Load all test failed:', err)
  }
}

// Infinite scroll setup using Intersection Observer
const setupInfiniteScroll = () => {
  // Wait a bit for the DOM to be ready
  setTimeout(() => {
    const photoGridContent = document.querySelector('.photo-grid-content')
    if (!photoGridContent) {
      console.log('Photo grid content not found, retrying...')
      setTimeout(setupInfiniteScroll, 1000)
      return
    }
    
    // Remove any existing sentinel and observer
    const existingSentinel = document.getElementById('infinite-scroll-sentinel')
    if (existingSentinel) {
      existingSentinel.remove()
    }
    
    if (window.infiniteScrollObserver) {
      window.infiniteScrollObserver.disconnect()
    }
    
    // Create a sentinel element at the bottom of the content
    const sentinel = document.createElement('div')
    sentinel.id = 'infinite-scroll-sentinel'
    sentinel.style.height = '20px'
    sentinel.style.width = '100%'
    sentinel.style.background = 'transparent'
    sentinel.style.pointerEvents = 'none' // Prevent any interaction
    
    // Add sentinel to the end of the content
    photoGridContent.appendChild(sentinel)
    
    console.log('Setting up infinite scroll with sentinel')
    
    // Create intersection observer with debouncing
    let isLoading = false
    const observer = new IntersectionObserver(
      (entries) => {
        const entry = entries[0]
        console.log('Sentinel intersection:', entry.isIntersecting, 'hasNextPage:', hasNextPage.value, 'loadingMore:', loadingMore.value, 'isLoading:', isLoading)
        
        if (entry.isIntersecting && hasNextPage.value && !loadingMore.value && !isLoading) {
          isLoading = true
          console.log('Loading more assets...')
          
          // Temporarily disconnect observer to prevent multiple triggers
          observer.disconnect()
          
          loadMoreAssets().finally(() => {
            // Reconnect observer after loading is complete
            setTimeout(() => {
              observer.observe(sentinel)
              isLoading = false
            }, 500)
          })
        }
      },
      {
        root: photoGridContent,
        rootMargin: '100px', // Reduced from 200px to be less aggressive
        threshold: 0.1
      }
    )
    
    observer.observe(sentinel)
    
    // Store observer for cleanup
    window.infiniteScrollObserver = observer
  }, 500)
}

// Fetch assets when component mounts
onMounted(async () => {
  await fetchTimeline()
  sectionObserver.current = new IntersectionObserver((entries) => {
    for (const entry of entries) {
      if (entry.isIntersecting) {
        const date = elToDate.get(entry.target)
        if (date) {
          currentDate.value = date
          loadDateAssets(date)
        }
      }
    }
  }, { root: null, rootMargin: '200px', threshold: 0.1 })

  // Preload the first couple of dates so content appears immediately
  if (timelineItems.value && timelineItems.value.length) {
    const preload = timelineItems.value.slice(0, 2)
    for (const item of preload) {
      loadDateAssets(item.date)
    }
  }

  // SSE: refresh the currently visible date section on asset_ready
  if ($events?.onAssetReady) {
    $events.onAssetReady(async () => {
      try {
        // Reload current date bucket and maybe the previous one for smoothness
        const cur = currentDate.value
        if (cur) {
          // Clear and reload the date assets
          delete dateAssets[cur]
          await loadDateAssets(cur)
        }
      } catch {}
    })
  }

  // Initialize scroll tracking after mount
  // Track active date smoothly on scroll (bind after DOM paints)
  setTimeout(() => {
    updateActiveOnScroll()
    if (contentRef.value && contentRef.value.addEventListener) {
      contentRef.value.addEventListener('scroll', updateActiveOnScroll, { passive: true })
    } else {
      window.addEventListener('scroll', updateActiveOnScroll, { passive: true })
    }
  }, 0)
})

onUnmounted(() => {
  if (sectionObserver.current) {
    sectionObserver.current.disconnect()
    sectionObserver.current = null
  }
  elToDate.clear()
  // No window resize handler required
  if (contentRef.value && contentRef.value.removeEventListener) {
    contentRef.value.removeEventListener('scroll', updateActiveOnScroll)
  } else {
    window.removeEventListener('scroll', updateActiveOnScroll)
  }
})

const openAsset = (asset) => {
  selectedAsset.value = asset
  showAssetDialog.value = true
}

const formatDate = (dateString) => {
  if (!dateString) return 'Unknown date'
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })
}

const formatDateHeader = (dateString) => {
  const date = new Date(dateString)
  const today = new Date()
  const yesterday = new Date(today)
  yesterday.setDate(yesterday.getDate() - 1)
  
  if (date.toDateString() === today.toDateString()) {
    return 'Today'
  } else if (date.toDateString() === yesterday.toDateString()) {
    return 'Yesterday'
  } else {
    return date.toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })
  }
}

// Group assets by date
const groupedAssets = computed(() => {
  const groups = {}
  
  assets.value.forEach(asset => {
    const date = new Date(asset.taken_at || asset.created_at)
    const dateKey = date.toISOString().split('T')[0] // YYYY-MM-DD format
    
    if (!groups[dateKey]) {
      groups[dateKey] = {
        date: dateKey,
        assets: []
      }
    }
    groups[dateKey].assets.push(asset)
  })
  
  // Sort by date (newest first)
  return Object.values(groups).sort((a, b) => new Date(b.date) - new Date(a.date))
})

// Generate timeline years from assets with months
const timelineYears = computed(() => {
  const yearData = {}
  
  assets.value.forEach(asset => {
    const date = new Date(asset.taken_at || asset.created_at)
    const year = date.getFullYear()
    const month = date.getMonth()
    
    if (!yearData[year]) {
      yearData[year] = {
        year: year,
        count: 0,
        months: {}
      }
    }
    
    yearData[year].count++
    
    if (!yearData[year].months[month]) {
      yearData[year].months[month] = 0
    }
    yearData[year].months[month]++
  })
  
  return Object.values(yearData)
    .sort((a, b) => b.year - a.year)
    .map(yearData => ({
      ...yearData,
      months: Object.entries(yearData.months)
        .map(([month, count]) => ({
          month: parseInt(month),
          count,
          name: new Date(0, month).toLocaleString('default', { month: 'short' })
        }))
        .sort((a, b) => b.month - a.month)
    }))
})

// Total photo count for display
const totalPhotoCount = computed(() => {
  return totalCount.value || assets.value.length
})

const selectYear = (year) => {
  selectedYear.value = selectedYear.value === year ? null : year
  // Scroll to first photo of that year
  const yearElement = document.querySelector(`[data-year="${year}"]`)
  if (yearElement) {
    yearElement.scrollIntoView({ behavior: 'smooth' })
  }
}

const selectMonth = (year, month) => {
  // Find the first photo from this year/month and scroll to it
  const targetDate = new Date(year, month, 1)
  const dateGroups = document.querySelectorAll('.date-group')
  
  for (const group of dateGroups) {
    const dateHeader = group.querySelector('.date-title')
    if (dateHeader) {
      const groupDate = new Date(dateHeader.textContent)
      if (groupDate.getFullYear() === year && groupDate.getMonth() === month) {
        group.scrollIntoView({ behavior: 'smooth', block: 'start' })
        break
      }
    }
  }
}

// Masonry is now handled by vue-masonry-wall library - no custom code needed!

// Flatten all loaded date buckets into a single, timeline-ordered list for the viewer
const viewerAssets = computed(() => {
  const list = []
  for (const item of timelineItems.value) {
    const arr = dateAssets[item.date]
    if (Array.isArray(arr) && arr.length) {
      // Keep the order as shown in each date's gallery
      list.push(...arr)
    }
  }
  return list
})

// Prefetch next timeline dates when user nears end of viewer list
const prefetchNextDates = async (count = 1) => {
  try {
    // Find last loaded date index
    let lastLoadedIdx = -1
    for (let i = 0; i < timelineItems.value.length; i++) {
      const d = timelineItems.value[i].date
      const arr = dateAssets[d]
      if (Array.isArray(arr) && arr.length) lastLoadedIdx = i
    }
    // Load the next N dates if available and not already loaded
    for (let k = 1; k <= count; k++) {
      const idx = lastLoadedIdx + k
      if (idx >= 0 && idx < timelineItems.value.length) {
        const date = timelineItems.value[idx].date
        if (!Array.isArray(dateAssets[date]) || dateAssets[date].length === 0) {
          await loadDateAssets(date)
        }
      }
    }
  } catch (e) {
    console.warn('Prefetch next dates failed', e)
  }
}

// Event handlers for ImageViewerV2
const handleAssetChanged = async (newAsset) => {
  selectedAsset.value = newAsset
  // If we are near the end of the currently available viewer list, prefetch next date section(s)
  const list = viewerAssets.value
  const idx = list.findIndex(a => a.id === newAsset?.id)
  if (idx >= 0 && idx >= list.length - 6) {
    await prefetchNextDates(2)
  }
}

const handleAssetDeleted = (deletedId) => {
  // Remove from flat assets list
  assets.value = assets.value.filter(a => a.id !== deletedId)
  // Also remove from any date buckets
  for (const k of Object.keys(dateAssets)) {
    const arr = dateAssets[k]
    if (Array.isArray(arr)) {
      dateAssets[k] = arr.filter(a => a.id !== deletedId)
    }
  }
  selectedAsset.value = null
}

// Set page title
useHead({
  title: 'OpenPhotobox - Your Family Photos'
})

// Timeline-based loading
const timelineItems = ref([]) // [{ date: 'YYYY-MM-DD', count: number }]
const dateAssets = reactive({}) // { [date]: Asset[] }
const sectionObserver = { current: null }
const elToDate = new Map()

const fetchTimeline = async () => {
  try {
    pending.value = true
    const res = await api.client.get('/api/assets/timeline/')
    if (res.success && res.data) {
      timelineItems.value = res.data.results || []
    } else {
      timelineItems.value = []
    }
  } catch (e) {
    error.value = e
  } finally {
    pending.value = false
  }
}

const loadDateAssets = async (date) => {
  if (!date || dateAssets[date]) return
  try {
    // placeholder to prevent duplicate requests
    dateAssets[date] = []
    const res = await api.client.get('/api/assets/by_date/', { date })
    const results = (res.success && res.data && res.data.results) ? res.data.results : []
    const mapped = results.map(a => ({
      ...a,
      src: a.thumbnail_url || a.original_url || a.storage_url,
      width: a.width || 1920,
      height: a.height || 1080,
      alt: a.description || 'Photo'
    }))
    dateAssets[date] = mapped
    // also append to flat list used by the viewer
    assets.value = assets.value.concat(mapped)
  } catch (e) {
    console.error('Failed to load photos for date', date, e)
    delete dateAssets[date]
  }
}

const registerDateSection = (el, date) => {
  if (!sectionObserver.current) return
  if (el) {
    elToDate.set(el, date)
    sectionObserver.current.observe(el)
  } else {
    for (const [k, v] of elToDate.entries()) {
      if (v === date) {
        sectionObserver.current.unobserve(k)
        elToDate.delete(k)
      }
    }
  }
}

// Compact slider-style timeline (years with month ticks)
const years = computed(() => {
  const set = new Set()
  for (const item of timelineItems.value) {
    const y = new Date(item.date).getFullYear()
    set.add(y)
  }
  return Array.from(set).sort((a, b) => b - a)
})

const monthsByYear = computed(() => {
  const map = {}
  for (const item of timelineItems.value) {
    const d = new Date(item.date)
    const y = d.getFullYear()
    const m = d.getMonth()
    if (!map[y]) map[y] = []
    if (!map[y].includes(m)) map[y].push(m)
  }
  for (const y of Object.keys(map)) {
    map[parseInt(y)].sort((a, b) => a - b)
  }
  return map
})

const scrollToYear = (year) => {
  const target = timelineItems.value.find(i => new Date(i.date).getFullYear() === year)
  if (target) {
    const el = document.getElementById('date-' + target.date)
    if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }
}

const scrollToYearMonth = (year, month) => {
  const target = timelineItems.value.find(i => {
    const d = new Date(i.date)
    return d.getFullYear() === year && d.getMonth() === month
  })
  if (target) {
    const el = document.getElementById('date-' + target.date)
    if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }
}

// Compactness controls for slider (static thinning)
const yearLabelStep = computed(() => {
  const len = years.value.length || 0
  if (len > 40) return 5
  if (len > 20) return 3
  return 2
})
const shouldShowYear = (idx) => (idx % yearLabelStep.value) === 0

// Track current visible date for slider highlight/progress
const currentDate = ref(null)
const activeYear = computed(() => currentDate.value ? new Date(currentDate.value).getFullYear() : null)
const activeMonth = computed(() => currentDate.value ? new Date(currentDate.value).getMonth() : null)
const progressPercent = computed(() => {
  const len = timelineItems.value.length
  if (!len) return 0
  const idx = timelineItems.value.findIndex(i => i.date === currentDate.value)
  if (idx < 0) return 0
  return (idx / Math.max(1, len - 1)) * 100
})

// Content container reference for scroll calculations
const contentRef = ref(null)

// Update active date based on scroll position for smoother indicator
const updateActiveOnScroll = () => {
  if (!contentRef.value) return
  const containerRect = contentRef.value.getBoundingClientRect()
  const headerOffset = 80
  let underTop = -Infinity
  let underDate = null
  let overTop = Infinity
  let overDate = null
  for (const item of timelineItems.value) {
    const el = document.getElementById('date-' + item.date)
    if (!el || !el.getBoundingClientRect) continue
    const r = el.getBoundingClientRect()
    const topRel = r.top - containerRect.top
    if (topRel <= headerOffset && topRel > underTop) {
      underTop = topRel
      underDate = item.date
    } else if (topRel > headerOffset && topRel < overTop) {
      overTop = topRel
      overDate = item.date
    }
  }
  const chosen = underDate || overDate || (timelineItems.value[0] && timelineItems.value[0].date)
  if (chosen) currentDate.value = chosen
}
</script>

<template>
  <div class="modern-timeline">
    <!-- Loading State -->
    <div v-if="pending" class="loading-container">
      <v-progress-circular size="64" color="primary" indeterminate></v-progress-circular>
      <div class="text-h6 mt-4">Loading your photos...</div>
    </div>
    
    <!-- Error State -->
    <div v-else-if="error" class="error-container">
      <v-icon size="64" color="error" class="mb-4">mdi-alert-circle</v-icon>
      <div class="text-h6 mb-2">Failed to load photos</div>
      <div class="text-body-1 text-medium-emphasis mb-4">{{ error?.message || 'Unknown error' }}</div>
      <v-btn color="primary" @click="fetchAssets">Try Again</v-btn>
    </div>
    
    <!-- Empty State -->
    <div v-else-if="!timelineItems.length" class="empty-container">
      <v-icon size="64" color="grey" class="mb-4">mdi-image-off</v-icon>
      <div class="text-h6 mb-2">No photos found</div>
      <div class="text-body-1 text-medium-emphasis mb-4">
        Upload some photos to get started with your family archive
      </div>
      <v-btn color="primary" to="/upload" prepend-icon="mdi-cloud-upload">
        Upload Photos
      </v-btn>
    </div>
    
    <!-- Main Content: Timeline with per-day lazy galleries -->
    <div v-else class="main-content-with-timeline">
      <!-- Compact Timeline Slider -->
      <div class="timeline-slider">
        <div class="years">
          <div class="to-top" @click="() => window.scrollTo({ top: 0, behavior: 'smooth' })">Top</div>
          <div
            v-for="(y, yi) in years"
            :key="y"
            class="year"
            @click="() => scrollToYear(y)"
          >
            <span class="year-label" v-show="shouldShowYear(yi)">{{ y }}</span>
            <div class="months">
              <div
                v-for="m in monthsByYear[y]"
                :key="y + '-' + m"
                class="month-tick"
                :title="new Date(y, m, 1).toLocaleString('default', { month: 'short', year: 'numeric' })"
                @click.stop="() => scrollToYearMonth(y, m)"
                :class="{ active: activeYear === y && activeMonth === m }"
              />
            </div>
            <div class="year-highlight" :class="{ active: activeYear === y }" />
          </div>
        </div>
      </div>

      <!-- Photo Grid Content -->
      <div class="photo-grid-content" :class="{ 'sidebar-collapsed': sidebarCollapsed }" ref="contentRef">
        <div class="timeline-photos">
          <div
            v-for="item in timelineItems"
            :key="item.date"
            class="date-section"
            :id="'date-' + item.date"
            :data-year="new Date(item.date).getFullYear()"
            :ref="el => registerDateSection(el, item.date)"
          >
            <!-- Date Header -->
            <div class="date-header">
              <h2 class="date-title">{{ new Date(item.date).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }) }}</h2>
              <div class="date-count">{{ item.count }} photos</div>
            </div>

            <!-- Per-date Justified Gallery -->
            <JustifiedGallery
              v-if="dateAssets[item.date]?.length"
              :images="dateAssets[item.date]"
              :targetRowHeight="220"
              :gap="4"
              :overscanPx="800"
              :externalScrollEl="'.photo-grid-content'"
              lastRow="left"
              @item-click="openAsset"
            />

            <div v-else class="loading-more-container">
              <v-progress-circular size="32" color="primary" indeterminate></v-progress-circular>
              <div class="text-body-2 mt-2">Loading photos...</div>
            </div>
          </div>
        </div>
      </div>
    </div>
    

    <!-- Image Viewer V2 -->
    <ImageViewerV2
      v-model="showAssetDialog"
      :asset="selectedAsset"
      :assets="viewerAssets"
      @asset-changed="handleAssetChanged"
      @asset-deleted="handleAssetDeleted"
    />
  </div>
</template>

<style scoped>
.modern-timeline { min-height: 100vh; overflow: hidden; }

.loading-container,
.error-container,
.empty-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
  text-align: center;
  padding: 2rem;
}

.loading-container {
  background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);
}

.error-container {
  background: linear-gradient(135deg, #fef2f2 0%, #fee2e2 100%);
}

.empty-container {
  background: linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%);
}

/* Dark theme adjustments */
:deep(.v-theme--dark) .loading-container {
  background: linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 100%);
}

:deep(.v-theme--dark) .error-container {
  background: linear-gradient(135deg, #1f1a1a 0%, #2d1a1a 100%);
}

:deep(.v-theme--dark) .empty-container {
  background: linear-gradient(135deg, #1a1f1a 0%, #1a2d1a 100%);
}

.main-content-with-timeline { display: grid; grid-template-columns: 56px 1fr; min-height: 100vh; width: 100%; }

/* Compact slider timeline */
.timeline-slider { width: 56px; border-right: 1px solid rgba(0, 0, 0, 0.06); background: rgba(255, 255, 255, 0.5); backdrop-filter: blur(6px); position: sticky; top: 64px; height: calc(100vh - 64px); overflow-y: hidden; display: grid; grid-template-columns: 1fr; z-index: 10; }
.years { padding: 0.25rem; display: flex; flex-direction: column; gap: 0.5rem; }
.to-top { font-size: 0.7rem; text-align: center; padding: 0.15rem 0; cursor: pointer; color: rgb(var(--v-theme-primary)); opacity: 0.8; }
.to-top:hover { opacity: 1; }
.main-content-with-timeline { align-items: start; }
.year { display: flex; flex-direction: column; align-items: center; gap: 0.15rem; }
.year-label { font-size: 0.75rem; font-weight: 600; color: rgb(var(--v-theme-on-surface)); opacity: 0.8; }
.months { display: flex; flex-direction: column; gap: 1px; }
.month-tick { width: 3px; height: 6px; background: rgba(var(--v-theme-primary), 0.35); border-radius: 1px; margin: 0 auto; cursor: pointer; }
.month-tick:hover { background: rgb(var(--v-theme-primary)); }
.month-tick.active { background: rgb(var(--v-theme-primary)); }
.year-highlight { width: 24px; height: 2px; background: transparent; border-radius: 1px; }
.year-highlight.active { background: rgba(var(--v-theme-primary), 0.6); }
.progress-bar { grid-column: 2; position: sticky; top: 0; height: 100vh; background: rgba(0,0,0,0.05); }
.progress { width: 100%; background: rgb(var(--v-theme-primary)); transition: height 0.15s linear; }

.sidebar-toggle {
  position: absolute;
  top: 1rem;
  right: 1rem;
  z-index: 10;
  background: rgba(255, 255, 255, 0.9) !important;
  backdrop-filter: blur(10px);
}

.timeline-nav {
  padding: 1rem;
  padding-top: 3rem;
}

.timeline-header {
  margin-bottom: 1.5rem;
}

.total-count {
  font-size: 0.875rem;
  color: rgb(var(--v-theme-primary));
  background: rgba(var(--v-theme-primary), 0.1);
  padding: 0.25rem 0.75rem;
  border-radius: 12px;
  font-weight: 600;
  display: inline-block;
}

.timeline-years {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.timeline-year-group {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.timeline-year {
  padding: 0.75rem;
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.2s ease;
  border: 1px solid transparent;
}

.timeline-year:hover {
  background: rgba(var(--v-theme-primary), 0.1);
  border-color: rgba(var(--v-theme-primary), 0.2);
}

.timeline-year.active {
  background: rgba(var(--v-theme-primary), 0.15);
  border-color: rgba(var(--v-theme-primary), 0.3);
}

.year-label {
  font-weight: 600;
  font-size: 1.1rem;
  color: rgb(var(--v-theme-on-surface));
}

.year-count {
  font-size: 0.875rem;
  color: rgb(var(--v-theme-primary));
  margin-top: 0.25rem;
  font-weight: 600;
}

.timeline-months {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
  margin-left: 1rem;
  padding-left: 0.5rem;
  border-left: 2px solid rgba(var(--v-theme-primary), 0.2);
}

.timeline-month {
  padding: 0.5rem 0.75rem;
  border-radius: 3px;
  cursor: pointer;
  transition: all 0.2s ease;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.timeline-month:hover {
  background: rgba(var(--v-theme-primary), 0.08);
}

.month-label {
  font-size: 0.875rem;
  color: rgb(var(--v-theme-on-surface));
  font-weight: 500;
}

.month-count {
  font-size: 0.75rem;
  color: rgb(var(--v-theme-primary));
  background: rgba(var(--v-theme-primary), 0.15);
  padding: 0.125rem 0.5rem;
  border-radius: 10px;
  font-weight: 600;
}

.photo-grid-content { overflow-y: auto; transition: all 0.3s ease; overflow-anchor: none; width: 100%; }

.photo-grid-content.sidebar-collapsed {
  margin-left: 0;
}

.timeline-photos { padding: 1rem; width: 100%; margin: 0; overflow-anchor: none; }

.date-section { margin-bottom: 1.5rem; }

.date-header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 0.75rem; padding-bottom: 0.25rem; border-bottom: 2px solid rgba(var(--v-theme-primary), 0.2); }

.date-title {
  font-size: 1.5rem;
  font-weight: 700;
  color: rgb(var(--v-theme-on-surface));
  margin: 0;
}

.date-count {
  font-size: 0.875rem;
  color: rgb(var(--v-theme-primary));
  background: rgba(var(--v-theme-primary), 0.15);
  padding: 0.25rem 0.75rem;
  border-radius: 12px;
  font-weight: 600;
}

/* JustifiedGallery component handles all photo grid styling */

.debug-info {
  position: fixed;
  top: 10px;
  right: 10px;
  background: rgba(0, 0, 0, 0.8);
  color: white;
  padding: 10px;
  border-radius: 5px;
  font-size: 12px;
  z-index: 1000;
}

/* Responsive adjustments */
@media (max-width: 768px) {
  .timeline-photos {
    padding: 1rem;
  }
  
  .date-title {
    font-size: 1.25rem;
  }
}

@media (max-width: 480px) {
  .date-title {
    font-size: 1.1rem;
  }
}

/* Dark theme adjustments */
:deep(.v-theme--dark) .timeline-sidebar {
  background: rgba(26, 26, 26, 0.95);
  border-right-color: rgba(255, 255, 255, 0.12);
}

:deep(.v-theme--dark) .sidebar-toggle {
  background: rgba(26, 26, 26, 0.9) !important;
}

/* Loading more and end of content indicators */
.loading-more-container,
.load-more-container,
.end-of-content,
.debug-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 2rem;
  margin: 2rem 0;
}

.debug-container {
  background: rgba(255, 193, 7, 0.1);
  border: 1px solid rgba(255, 193, 7, 0.3);
  border-radius: 8px;
  text-align: center;
}

.debug-info {
  margin-bottom: 1rem;
  font-size: 0.875rem;
  color: rgb(var(--v-theme-on-surface));
}

.debug-info p {
  margin: 0.25rem 0;
}

.loading-more-container {
  background: rgba(var(--v-theme-primary), 0.05);
  border-radius: 12px;
  border: 1px dashed rgba(var(--v-theme-primary), 0.2);
}

.load-more-container {
  position: relative;
  z-index: 1;
}

.load-more-btn {
  background: rgb(var(--v-theme-primary));
  color: rgb(var(--v-theme-on-primary));
  border: 2px solid rgb(var(--v-theme-primary));
  border-radius: 8px;
  padding: 12px 24px;
  font-size: 16px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.3s ease;
  position: relative;
  z-index: 2;
  min-width: 200px;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
}

.load-more-btn:hover:not(:disabled) {
  background: rgba(var(--v-theme-primary), 0.9);
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(var(--v-theme-primary), 0.3);
}

.load-more-btn:disabled {
  background: rgba(var(--v-theme-primary), 0.5);
  cursor: not-allowed;
  transform: none;
  box-shadow: none;
}

.loading-spinner {
  width: 16px;
  height: 16px;
  border: 2px solid rgba(255, 255, 255, 0.3);
  border-top: 2px solid white;
  border-radius: 50%;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.end-of-content {
  color: rgb(var(--v-theme-on-surface-variant));
  font-style: italic;
}

/* Responsive adjustments for timeline */
@media (max-width: 768px) {
  .timeline-sidebar {
    position: fixed;
    top: 0;
    left: 0;
    height: 100vh;
    z-index: 1000;
    transform: translateX(-100%);
  }
  
  .timeline-sidebar:not(.collapsed) {
    transform: translateX(0);
  }
  
  .photo-grid-content {
    width: 100%;
  }
  
  .timeline-photos {
    padding: 1rem;
  }
}
</style>